//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowTech_MasterReportList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlowTech_MasterReportList()
        {
            this.Rpt_PreCommissioningItemsList = new HashSet<Rpt_PreCommissioningItemsList>();
            this.tblSystemMasterReports = new HashSet<tblSystemMasterReport>();
            this.tblSystemReports = new HashSet<tblSystemReport>();
        }
    
        public System.Guid TemplateID { get; set; }
        public string DisplayName { get; set; }
        public string PageName { get; set; }
        public bool IsActive { get; set; }
        public string TableName { get; set; }
        public string ReportNumber { get; set; }
        public string RevisionNumber { get; set; }
        public bool IsDefectReport { get; set; }
        public bool IsInfoReport { get; set; }
        public bool IsTechniciansReport { get; set; }
        public bool IsVavSummary { get; set; }
        public bool Archived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rpt_PreCommissioningItemsList> Rpt_PreCommissioningItemsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSystemMasterReport> tblSystemMasterReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSystemReport> tblSystemReports { get; set; }
    }
}
