//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_SplitPackage
    {
        public System.Guid ReportID { get; set; }
        public Nullable<System.Guid> SystemReportID_fk { get; set; }
        public string FanLoc { get; set; }
        public string Manufacturer { get; set; }
        public string ModelNo { get; set; }
        public string SerialNo { get; set; }
        public string Capacity { get; set; }
        public string FanType { get; set; }
        public string FanArrange { get; set; }
        public string MSSBName { get; set; }
        public string MSSBLoc { get; set; }
        public string TotDes { get; set; }
        public string TotAct { get; set; }
        public string OutDes { get; set; }
        public string OutAct { get; set; }
        public string ReturnDes { get; set; }
        public string ReturnAct { get; set; }
        public string ExtDes { get; set; }
        public string ExtAct { get; set; }
        public string SucDes { get; set; }
        public string SucAct { get; set; }
        public string DisDes { get; set; }
        public string DisAct { get; set; }
        public string MotorMake { get; set; }
        public string FrameClass { get; set; }
        public string ElectSupply { get; set; }
        public string MotorPower { get; set; }
        public string FullLoadAmps { get; set; }
        public string Pole { get; set; }
        public string RPM { get; set; }
        public string FuseDetails { get; set; }
        public string FanDia { get; set; }
        public string FanBush { get; set; }
        public string FanBore { get; set; }
        public string MotorDia { get; set; }
        public string MotorBush { get; set; }
        public string MotorBore { get; set; }
        public string BeltsMake { get; set; }
        public string BeltsNo { get; set; }
        public string BeltsSize { get; set; }
        public string ShaftCentre { get; set; }
        public string FilterType { get; set; }
        public string FilterSize { get; set; }
        public string NoOfFilters { get; set; }
        public string Location { get; set; }
        public string CondManu { get; set; }
        public string CondMNo { get; set; }
        public string CondSNo { get; set; }
        public string CompManu { get; set; }
        public string CompModNo { get; set; }
        public string CompElec { get; set; }
        public string CompFull { get; set; }
        public string Ref { get; set; }
        public string Kg { get; set; }
        public string HeatingType { get; set; }
        public string CondFanMake { get; set; }
        public string CondFanNo { get; set; }
        public string CondFan { get; set; }
        public string MotorPowerC { get; set; }
        public string FullLoadAmpsC { get; set; }
        public string PoleC { get; set; }
        public string RPMC { get; set; }
        public string FuseDetailsC { get; set; }
        public string SupS1 { get; set; }
        public string SupS2 { get; set; }
        public string SupS3 { get; set; }
        public string SupS4 { get; set; }
        public string CompS1 { get; set; }
        public string CompS2 { get; set; }
        public string CompS3 { get; set; }
        public string CompS4 { get; set; }
        public string CompVoltS1 { get; set; }
        public string CompVoltS2 { get; set; }
        public string CompVoltS3 { get; set; }
        public string CompVoltS4 { get; set; }
        public string AmbiS1 { get; set; }
        public string AmbiS2 { get; set; }
        public string AmbiS3 { get; set; }
        public string AmbiS4 { get; set; }
        public string SucS1 { get; set; }
        public string SucS2 { get; set; }
        public string SucS3 { get; set; }
        public string SucS4 { get; set; }
        public string DisS1 { get; set; }
        public string DisS2 { get; set; }
        public string DisS3 { get; set; }
        public string DisS4 { get; set; }
        public string OilS1 { get; set; }
        public string OilS2 { get; set; }
        public string OilS3 { get; set; }
        public string OilS4 { get; set; }
        public string CompSucS1 { get; set; }
        public string CompSucS2 { get; set; }
        public string CompSucS3 { get; set; }
        public string CompSucS4 { get; set; }
        public string LiqS1 { get; set; }
        public string LiqS2 { get; set; }
        public string LiqS3 { get; set; }
        public string LiqS4 { get; set; }
        public string SuperS1 { get; set; }
        public string SuperS2 { get; set; }
        public string SuperS3 { get; set; }
        public string SuperS4 { get; set; }
        public string SubS1 { get; set; }
        public string SubS2 { get; set; }
        public string SubS3 { get; set; }
        public string SubS4 { get; set; }
        public string EvapEntering1 { get; set; }
        public string EvapEntering2 { get; set; }
        public string EvapEntering3 { get; set; }
        public string EvapEntering4 { get; set; }
        public string EvapLeaving1 { get; set; }
        public string EvapLeaving2 { get; set; }
        public string EvapLeaving3 { get; set; }
        public string EvapLeaving4 { get; set; }
        public string CondVoltS1 { get; set; }
        public string CondVoltS2 { get; set; }
        public string CondVoltS3 { get; set; }
        public string CondVoltS4 { get; set; }
        public string FCondAmpsS1 { get; set; }
        public string FCondAmpsS2 { get; set; }
        public string FCondAmpsS3 { get; set; }
        public string FCondAmpsS4 { get; set; }
        public string ICAComments { get; set; }
        public string Capacity2 { get; set; }
        public string FuseDetailsMDPH { get; set; }
        public string Kg2 { get; set; }
        public string Kg3 { get; set; }
        public string Kg4 { get; set; }
        public string FuseDetailsCMDPH { get; set; }
        public string FilterSizeB { get; set; }
        public string FilterSizeC { get; set; }
        public string HeadBuilding { get; set; }
        public string HeadService { get; set; }
        public string HeadCustomer { get; set; }
    
        public virtual tblSystemReport tblSystemReport { get; set; }
    }
}
