//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_AirbalanceZones
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ReportID_fk { get; set; }
        public string BranchRef { get; set; }
        public string AreaZone { get; set; }
        public Nullable<int> NoGrilles { get; set; }
        public string GrilleType { get; set; }
        public Nullable<double> SizeA { get; set; }
        public Nullable<double> SizeB { get; set; }
        public Nullable<double> Factor { get; set; }
        public Nullable<double> CorrectedArea { get; set; }
        public string TestApparatus { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ZoneType { get; set; }
        public string GrilleRef { get; set; }
        public double DesFlow { get; set; }
    
        public virtual Rpt_AirBalance Rpt_AirBalance { get; set; }
    }
}
