//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_PumpCommissioning
    {
        public System.Guid ReportID { get; set; }
        public Nullable<System.Guid> SystemReportID_fk { get; set; }
        public string LocationPump { get; set; }
        public string WaterTypePump { get; set; }
        public string SBoardRef { get; set; }
        public string SBoardLoc { get; set; }
        public string ManufacturePump { get; set; }
        public string ModelNoPump { get; set; }
        public string SerialNoPump { get; set; }
        public string PumpType { get; set; }
        public string ImpSize { get; set; }
        public string PumpLs { get; set; }
        public string PumpKPA { get; set; }
        public string CoilVesselLs { get; set; }
        public string CoilVesselKPA { get; set; }
        public string MotorMakeMD { get; set; }
        public string FrameMD { get; set; }
        public string ElectricalMD { get; set; }
        public string MotorPowerMD { get; set; }
        public string FullLoadMD { get; set; }
        public string PoleMD { get; set; }
        public string PoleRPMMD { get; set; }
        public string FuseDetailsMD { get; set; }
        public string OverloadMakeMS { get; set; }
        public string OverloadRangeMS { get; set; }
        public string VSDMakeMS { get; set; }
        public string VSDRangeMS { get; set; }
        public string SystemOpp { get; set; }
        public string TestPoint { get; set; }
        public string Aligned { get; set; }
        public string Strainer { get; set; }
        public string Curve { get; set; }
        public string Suction1 { get; set; }
        public string Discharge1 { get; set; }
        public string Delta1 { get; set; }
        public string RPM1 { get; set; }
        public string Amps1 { get; set; }
        public string Hz1 { get; set; }
        public string Suction2 { get; set; }
        public string Discharge2 { get; set; }
        public string Delta2 { get; set; }
        public string RPM2 { get; set; }
        public string Amps2 { get; set; }
        public string Hz2 { get; set; }
        public string Suction3 { get; set; }
        public string Discharge3 { get; set; }
        public string Delta3 { get; set; }
        public string RPM3 { get; set; }
        public string Amps3 { get; set; }
        public string Hz3 { get; set; }
        public string ClosedPressure { get; set; }
        public string OpenPressure { get; set; }
        public string ClosedHz { get; set; }
        public string OpenHz { get; set; }
        public string PumpFinalLS { get; set; }
        public string PumpFinalKPA { get; set; }
        public string PumpFinalHz { get; set; }
        public string PumpOp { get; set; }
        public string PumpStatic { get; set; }
        public string Instrument1 { get; set; }
        public string Model1 { get; set; }
        public string Serial1 { get; set; }
        public string Instrument2 { get; set; }
        public string Model2 { get; set; }
        public string Serial2 { get; set; }
        public string TechnicianComments { get; set; }
        public string ICAComments { get; set; }
        public string FuseDetailsMDPH { get; set; }
        public string OverloadRangeMS2 { get; set; }
        public string OverloadRangeMS3 { get; set; }
        public string FullFlowLS { get; set; }
        public string FinalFlowLS { get; set; }
        public string HeadBuilding { get; set; }
        public string HeadService { get; set; }
        public string HeadCustomer { get; set; }
        public string BMSPumpSpeed { get; set; }
        public string BMSVelocity { get; set; }
        public string BMSPressure { get; set; }
        public string BMSOther { get; set; }
        public string PumpFinalFinLs { get; set; }
        public string PumpFinalFinKPa { get; set; }
        public string PumpFinalFinPer { get; set; }
        public string CoilLs { get; set; }
        public string CoilKPa { get; set; }
        public string CoilFinLs { get; set; }
        public string CoilFinKPa { get; set; }
        public string CoilFinPer { get; set; }
        public string WitnessName { get; set; }
        public Nullable<System.DateTime> WitnessDate { get; set; }
        public string WitnessSignature { get; set; }
        public string BMSPumpSpeedType { get; set; }
        public string BMSVelocityType { get; set; }
    
        public virtual tblSystemReport tblSystemReport { get; set; }
    }
}
