//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_VavCommissioningVavs
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ReportID_fk { get; set; }
        public string VavReference { get; set; }
        public Nullable<int> NoGrilles { get; set; }
        public string VavManufacturer { get; set; }
        public string VavType { get; set; }
        public string ReheatType { get; set; }
        public string GrilleType { get; set; }
        public Nullable<int> GrilleSizeX { get; set; }
        public Nullable<int> GrilleSizeY { get; set; }
        public Nullable<double> GrilleFactor { get; set; }
        public string TestApp { get; set; }
        public Nullable<double> VMin { get; set; }
        public Nullable<double> VMax { get; set; }
        public Nullable<double> ResultsDesVMin { get; set; }
        public Nullable<double> ResultsDesVMax { get; set; }
        public Nullable<double> ResultsFinVMin { get; set; }
        public Nullable<double> ResultsFinVMax { get; set; }
        public string BmsKFactor { get; set; }
        public Nullable<double> BmsVMin { get; set; }
        public Nullable<double> BmsVMax { get; set; }
        public Nullable<double> BMSLsTotal { get; set; }
        public string BMSDamperPosition { get; set; }
        public Nullable<double> InletSize { get; set; }
    
        public virtual Rpt_VavCommissioning Rpt_VavCommissioning { get; set; }
    }
}
