//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGroupSystem()
        {
            this.tblSystemMasterReports = new HashSet<tblSystemMasterReport>();
            this.tblSystemReports = new HashSet<tblSystemReport>();
        }
    
        public System.Guid SystemID { get; set; }
        public Nullable<System.Guid> GroupID_fk { get; set; }
        public string Reference { get; set; }
        public string Service { get; set; }
    
        public virtual tblProjectGroup tblProjectGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSystemMasterReport> tblSystemMasterReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSystemReport> tblSystemReports { get; set; }
    }
}
