//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectTechnician
    {
        public System.Guid ProjectTechnicianID { get; set; }
        public Nullable<System.Guid> ProjectID_fk { get; set; }
        public string UserID_fk { get; set; }
    
        public virtual tblProject tblProject { get; set; }
    }
}
