//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemMasterReport
    {
        public System.Guid SystemMasterReportID { get; set; }
        public Nullable<System.Guid> SystemID_fk { get; set; }
        public Nullable<System.Guid> TemplateID_fk { get; set; }
    
        public virtual FlowTech_MasterReportList FlowTech_MasterReportList { get; set; }
        public virtual tblGroupSystem tblGroupSystem { get; set; }
    }
}
