//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSystemReport()
        {
            this.Rpt_PreCommissioning = new HashSet<Rpt_PreCommissioning>();
            this.Rpt_FcuCommissioning = new HashSet<Rpt_FcuCommissioning>();
            this.Rpt_FcuCommissioningDirectDrive = new HashSet<Rpt_FcuCommissioningDirectDrive>();
            this.tblSystemReportComments = new HashSet<tblSystemReportComment>();
            this.Rpt_VavCommissioning = new HashSet<Rpt_VavCommissioning>();
            this.Rpt_AirBalance = new HashSet<Rpt_AirBalance>();
            this.Rpt_PumpCommissioning = new HashSet<Rpt_PumpCommissioning>();
            this.Rpt_SplitPackage = new HashSet<Rpt_SplitPackage>();
        }
    
        public System.Guid SystemReportID { get; set; }
        public Nullable<System.Guid> SystemID_fk { get; set; }
        public Nullable<System.Guid> TemplateID_fk { get; set; }
        public string Name { get; set; }
        public string TestReference { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual FlowTech_MasterReportList FlowTech_MasterReportList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rpt_PreCommissioning> Rpt_PreCommissioning { get; set; }
        public virtual tblGroupSystem tblGroupSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rpt_FcuCommissioning> Rpt_FcuCommissioning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rpt_FcuCommissioningDirectDrive> Rpt_FcuCommissioningDirectDrive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSystemReportComment> tblSystemReportComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rpt_VavCommissioning> Rpt_VavCommissioning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rpt_AirBalance> Rpt_AirBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rpt_PumpCommissioning> Rpt_PumpCommissioning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rpt_SplitPackage> Rpt_SplitPackage { get; set; }
    }
}
