//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemReportComment
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> SysRepID_fk { get; set; }
        public Nullable<System.Guid> TechnicianID_fk { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Comments { get; set; }
    
        public virtual tblSystemReport tblSystemReport { get; set; }
    }
}
